spring:
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.102.99.184:3306/panda-boss-note?useUnicode=true&characterEncoding=utf-8
      username: panda-note
      password: panda
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

  #redis配置
  redis:
    database: 1
    host: 47.102.99.184
    port: 6379
    password: wjh_redis123.
    # 连接超时时间
    timeout: 3000
    pool:
      # 接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接池中的最大空闲连接
      max-idle: 8
      test-on-return: true
      # 在获取连接的时候检查有效性
      test-on-borrow: true
      # 在空闲时检查有效性
      test-while-idle: true

druid:
  monitor:
    ip:
      allow: 127.0.0.1
      deny:
    login:
      username: admin
      password: admin
    reset: true

request:
  http:
    file:
      intranet: http://120.79.216.133/file
      internet: http://120.79.216.133/file
#      intranet: http://127.0.0.1:12401/file
#      internet: http://127.0.0.1:12401/file
